# location_names.py

translation_dict = {
    # 国家
    "CN": "中国",
    "HK": "中国香港",
    "TW": "中国台湾",
    "US": "美国",
    "JP": "日本",
    "KR": "韩国",
    "DE": "德国",
    "FR": "法国",
    "GB": "英国",
    "IN": "印度",
    "BR": "巴西",
    "RU": "俄罗斯",
    "AU": "澳大利亚",
    "CA": "加拿大",
    "SG": "新加坡",
    "MY": "马来西亚",
    "TH": "泰国",
    "VN": "越南",
    "NL": "荷兰",
    #----------------------------
    # CN省
    "BJ": "北京",
    "SH": "上海",
    "FJ": "福建",
    "GD": "广东",
    "ZJ": "浙江",
    "JS": "江苏",
    "SD": "山东",
    "AH": "安徽",
    "HB": "湖北",
    "HN": "湖南",
    "SX": "山西",
    "JL": "吉林",
    "LN": "辽宁",
    "NM": "内蒙古",
    "GX": "广西",
    "XZ": "西藏",
    "QH": "青海",
    "GS": "甘肃",
    "NX": "宁夏",
    "XJ": "新疆",
    "SC": "四川",
    "GZ": "贵州",
    "YN": "云南",
    "HLJ": "黑龙江",
    "JS": "江苏",
    "AH": "安徽",
    "SD": "山东",
    "GX": "广西",
    "QH": "青海",
    "XZ": "西藏",
    "HA": "河南",

    # CN市
    "Beijing": "北京",
    "Shanghai": "上海",
    "Guangzhou": "广州",
    "Shenzhen": "深圳",
    "Hangzhou": "杭州",
    "Nanjing": "南京",
    "Wuhan": "武汉",
    "Chengdu": "成都",
    "Xian": "西安",
    "Chongqing": "重庆",
    "Tianjin": "天津",
    "Suzhou": "苏州",
    "Dongguan": "东莞",
    "Shijiazhuang": "石家庄",
    "Ningbo": "宁波",
    "Qingdao": "青岛",
    "Dalian": "大连",
    "Zhengzhou": "郑州",
    "Jinan": "济南",
    "Xiamen": "厦门",
    "Fuzhou": "福州",
    "Changsha": "长沙",
    "Nanchang": "南昌",
    "Haikou": "海口",
    "Lanzhou": "兰州",
    "Hefei": "合肥",
    "Taiyuan": "太原",
    "Kunming": "昆明",
    "Urumqi": "乌鲁木齐",
    "Xining": "西宁",
    "Yinchuan": "银川",
    "Lijiang": "丽江",
    "Zhangjiajie": "张家界",
    "Hohhot": "呼和浩特",
    "Wuxi": "无锡",
    "Foshan": "佛山",
    "Zhongshan": "中山",
    "Zhuhai": "珠海",
    "Xuzhou": "徐州",
    "Linyi": "临沂",
    "Yantai": "烟台",
    "Weifang": "潍坊",
    "Nantong": "南通",
    "Ningde": "宁德",
    "Zhangzhou": "漳州",
    "Quanzhou": "泉州",
    "Putian": "莆田",
    "Zaozhuang": "枣庄",
    "Jining": "济宁",
    "Heze": "菏泽",
    "Liaocheng": "聊城",
    "Dezhou": "德州",
    "Binzhou": "滨州",
    "Dongying": "东营",
    "Weihai": "威海",
    "Yantai": "烟台",
    "Qingdao": "青岛",
    "Zibo": "淄博",
    "Xinyang": "信阳",
    "Luoyang": "洛阳",
    "Kaifeng": "开封",
    "Pingdingshan": "平顶山",
    "Anyang": "安阳",
    "Hebi": "鹤壁",
    "Xinxiang": "新乡",
    "Zhengzhou": "郑州",
    "Ürümqi": "Ürümqi(乌鲁木齐)",
    "Nanning": "南宁",
    "Changzhi": "长治",
    #----------------------------
    # TW 省
    "TPE": "TPE(台北)",
    # TW 市
    "Taipei": "Taipei(台北)",
    #----------------------------
    # US 省
    "WA": "WA(华盛顿)",
    # US 市
    "Seattle": "Seattle(西雅图)",
    #----------------------------
    # JP 省
    # JP 市
    "Tokyo": "Tokyo(东京)",
    #----------------------------
    # CA 省
    # CA 市
    "Fremont": "Fremont(費利蒙)",
    #----------------------------
    # NL 省
    "NH": "NH(北荷兰)",
    # NL 市
    "Amsterdam": "Amsterdam(阿姆斯特丹)",
    #----------------------------
    # 可以在这里添加更多的翻译
}
