# location_names.py

translation_dict = {
    # 国家
    "CN": "中国",
    "HK": "中国香港",
    "TW": "中国台湾",
    "US": "美国",
    "JP": "日本",
    "KR": "韩国",
    "DE": "德国",
    "FR": "法国",
    "GB": "英国",
    "IN": "印度",
    "BR": "巴西",
    "RU": "俄罗斯",
    "AU": "澳大利亚",
    "CA": "CA(加利福尼亚/加拿大)",
    "SG": "新加坡",
    "MY": "马来西亚",
    "TH": "泰国",
    "VN": "越南",
    "NL": "荷兰",
    #----------------------------
    # CN省
    "BJ": "北京",
    "SH": "上海",
    "FJ": "福建",
    "GD": "广东",
    "ZJ": "浙江",
    "JS": "江苏",
    "SD": "山东",
    "AH": "安徽",
    "HB": "湖北",
    "HN": "湖南",
    "SX": "山西",
    "JL": "吉林",
    "LN": "辽宁",
    "NM": "内蒙古",
    "GX": "广西",
    "XZ": "西藏",
    "QH": "青海",
    "GS": "甘肃",
    "NX": "宁夏",
    "XJ": "新疆",
    "SC": "四川",
    "GZ": "贵州",
    "YN": "云南",
    "HLJ": "黑龙江",
    "HA": "河南",
    "TJ": "天津",

    # CN市
    "Beijing": "北京",
    "Shanghai": "上海",
    "Guangzhou": "广州",
    "Shenzhen": "深圳",
    "Hangzhou": "杭州",
    "Nanjing": "南京",
    "Wuhan": "武汉",
    "Chengdu": "成都",
    "Xian": "西安",
    "Chongqing": "重庆",
    "Tianjin": "天津",
    "Suzhou": "苏州",
    "Dongguan": "东莞",
    "Shijiazhuang": "石家庄",
    "Ningbo": "宁波",
    "Qingdao": "青岛",
    "Dalian": "大连",
    "Zhengzhou": "郑州",
    "Jinan": "济南",
    "Xiamen": "厦门",
    "Fuzhou": "福州",
    "Changsha": "长沙",
    "Nanchang": "南昌",
    "Haikou": "海口",
    "Lanzhou": "兰州",
    "Hefei": "合肥",
    "Taiyuan": "太原",
    "Kunming": "昆明",
    "Xining": "西宁",
    "Yinchuan": "银川",
    "Lijiang": "丽江",
    "Zhangjiajie": "张家界",
    "Hohhot": "呼和浩特",
    "Wuxi": "无锡",
    "Foshan": "佛山",
    "Zhongshan": "中山",
    "Zhuhai": "珠海",
    "Xuzhou": "徐州",
    "Linyi": "临沂",
    "Yantai": "烟台",
    "Weifang": "潍坊",
    "Nantong": "南通",
    "Ningde": "宁德",
    "Zhangzhou": "漳州",
    "Quanzhou": "泉州",
    "Putian": "莆田",
    "Zaozhuang": "枣庄",
    "Jining": "济宁",
    "Heze": "菏泽",
    "Liaocheng": "聊城",
    "Dezhou": "德州",
    "Binzhou": "滨州",
    "Dongying": "东营",
    "Weihai": "威海",
    "Yantai": "烟台",
    "Zibo": "淄博",
    "Xinyang": "信阳",
    "Luoyang": "洛阳",
    "Kaifeng": "开封",
    "Pingdingshan": "平顶山",
    "Anyang": "安阳",
    "Hebi": "鹤壁",
    "Xinxiang": "新乡",
    "Ürümqi": "Ürümqi(乌鲁木齐)",
    "Nanning": "南宁",
    "Changzhi": "长治",
    "Taishing": "泰兴",
    #----------------------------
    # TW 省
    "TPE": "TPE(台北)",
    # TW 市
    "Taipei": "Taipei(台北)",
    #----------------------------
    # HK 省
    "KKC": "KKC(九龙城区)",
    "Kowloon City": "Kowloon City(九龙城)",
    #----------------------------
    # SG
    "Singapore": "新加坡",
    #----------------------------
    # US 省
    "WA": "WA(华盛顿)",
    "CA": "CA(加利福尼亚/加拿大)",
    # US 市
    "Atlanta": "Atlanta(亚特兰大)",
    "Boston": "Boston(波士顿)",
    "Chicago": "Chicago(芝加哥)",
    "Dallas": "Dallas(达拉斯)",
    "Denver": "Denver(丹佛)",
    "Detroit": "Detroit(底特律)",
    "Houston": "Houston(休斯顿)",
    "LasVegas": "Las Vegas(拉斯维加斯)",
    "Los Angeles": "Los Angeles(洛杉矶)",
    "Miami": "Miami(迈阿密)",
    "NewYork": "New York(纽约)",
    "Philadelphia": "Philadelphia(费城)",
    "Phoenix": "Phoenix(菲尼克斯)",
    "SanAntonio": "San Antonio(圣安东尼奥)",
    "SanDiego": "San Diego(圣地亚哥)",
    "SanFrancisco": "San Francisco(旧金山)",
    "Seattle": "Seattle(西雅图)",
    "Washington": "Washington(华盛顿)",
    "Charlotte": "Charlotte(夏洛特)",
    "Portland": "Portland(波特兰)",
    "Indianapolis": "Indianapolis(印第安纳波利斯)",
    "Columbus": "Columbus(哥伦布)",
    "Jacksonville": "Jacksonville(杰克逊维尔)",
    "Memphis": "Memphis(孟菲斯)",
    "Milwaukee": "Milwaukee(密尔沃基)",
    "Boston": "Boston(波士顿)",
    "VirginiaBeach": "Virginia Beach(维吉尼亚海滩)",
    "Atlanta": "Atlanta(亚特兰大)",
    "Raleigh": "Raleigh(罗利)",
    "SaltLakeCity": "Salt Lake City(盐湖城)",
    "Louisville": "Louisville(路易斯维尔)",
    "NewOrleans": "New Orleans(新奥尔良)",
    "Detroit": "Detroit(底特律)",
    "Minneapolis": "Minneapolis(明尼阿波利斯)",
    "Oakland": "Oakland(奥克兰)",
    "StLouis": "St. Louis(圣路易斯)",
    "VirginiaBeach": "Virginia Beach(维吉尼亚海滩)",
    "Atlanta": "Atlanta(亚特兰大)",
    "ColoradoSprings": "Colorado Springs(科罗拉多斯普林斯)",
    "Arlington": "Arlington(阿灵顿)",
    "Anchorage": "Anchorage(安克雷奇)",
    "ChulaVista": "Chula Vista(丘拉维斯塔)",
    "SantaAna": "Santa Ana(圣安娜)",
    "CorpusChristi": "Corpus Christi(科珀斯克里斯蒂)",
    "StPaul": "St. Paul(圣保罗)",
    "Chandler": "Chandler(钱德勒)",
    "FortWorth": "Fort Worth(沃斯堡)",
    "Buffalo": "Buffalo(布法罗)",
    "Newark": "Newark(纽瓦克)",
    "Plano": "Plano(普莱诺)",
    "Lincoln": "Lincoln(林肯)",
    "Anchorage": "Anchorage(安克雷奇)",
    "Chattanooga": "Chattanooga(查塔努加)",
    "DesMoines": "Des Moines(得梅因)",
    "Madison": "Madison(麦迪逊)",
    "Reno": "Reno(里诺)",
    "Boise": "Boise(博伊西)",
    "Richmond": "Richmond(里士满)",
    "Mobile": "Mobile(莫比尔)",
    "GrandRapids": "Grand Rapids(大急流城)",
    "SaltLakeCity": "Salt Lake City(盐湖城)",
    "Springfield": "Springfield(斯普林菲尔德)",
    "OverlandPark": "Overland Park(奥弗兰公园)",
    "Tempe": "Tempe(坦佩)",
    "Peoria": "Peoria(皮奥里亚)",
    "SantaClarita": "Santa Clarita(圣克拉丽塔)",
    "Vancouver": "Vancouver(温哥华)",
    "Carrollton": "Carrollton(卡罗尔顿)",
    "WestValleyCity": "West Valley City(西谷城)",
    "Columbia": "Columbia(哥伦比亚)",
    "Waterbury": "Waterbury(沃特伯里)",
    "Chesapeake": "Chesapeake(切萨皮克)",
    "Sunnyvale": "Sunnyvale(阳光谷)",
    "Miramar": "Miramar(米拉玛)",
    "Cambridge": "Cambridge(剑桥)",
    "Peoria": "Peoria(皮奥里亚)",
    "Salem": "Salem(塞勒姆)",
    "Springfield": "Springfield(斯普林菲尔德)",
    "SantaMaria": "Santa Maria(圣玛丽亚)",
    "Westminster": "Westminster(威斯敏斯特)",
    "Carlsbad": "Carlsbad(卡尔斯巴德)",
    "WestJordan": "West Jordan(西乔丹)",
    "Lakewood": "Lakewood(莱克伍德)",
    "ElPaso": "El Paso(埃尔帕索)",
    "FortWayne": "Fort Wayne(韦恩堡)",
    "Tempe": "Tempe(坦佩)",
    "Chattanooga": "Chattanooga(查塔努加)",
    "GrandPrairie": "Grand Prairie(大草原)",
    "NorthLasVegas": "North Las Vegas(北拉斯维加斯)",
    "WestPalmBeach": "West Palm Beach(西棕榈滩)",
    "Carlsbad": "Carlsbad(卡尔斯巴德)",
    "Westminster": "Westminster(威斯敏斯特)",
    "Chesapeake": "Chesapeake(切萨皮克)",
    "Sunnyvale": "Sunnyvale(阳光谷)",
    "Miramar": "Miramar(米拉玛)",
    "Cambridge": "Cambridge(剑桥)",
    "Peoria": "Peoria(皮奥里亚)",
    "Salem": "Salem(塞勒姆)",
    #----------------------------
    # JP 省
    # JP 市
    "Tokyo": "Tokyo(东京)",
    #----------------------------
    # CA 省
    # CA 市
    "Fremont": "Fremont(費利蒙)",
    #----------------------------
    # NL 省
    "NH": "NH(北荷兰)",
    # NL 市
    "Amsterdam": "Amsterdam(阿姆斯特丹)",
    #----------------------------
    # 可以在这里添加更多的翻译
}
